apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask-backend
        image: hemamathiyazhagan/imagestore-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 3333
    targetPort: 3333